-- 修复 problem_basic 表的 id 字段为 AUTO_INCREMENT
ALTER TABLE `problem_basic` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;

-- 如果其他表也有同样的问题，也需要修复
ALTER TABLE `test_case` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `problem_category` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_basic` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `submit_basic` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `category_basic` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;

